services:
  - type: web
    name: resume-screener
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"
    startCommand: python app.py
