services:
  - type: web
    name: resume-screener
    env: docker
    plan: free  # or use "starter" if you increase memory
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
